#!/bin/bash
set -eu
root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
python3 - "$root" <<'PY'
import pathlib,sys,re,tarfile,gzip,hashlib,datetime
root=pathlib.Path(sys.argv[1]);metadata=(root/'lib/metadata.sh').read_text()
def field(name):return re.search(r"^"+name+r"='([^']+)'",metadata,re.M)[1]
version=field('GILLII_VERSION');date=field('GILLII_DATE');repo=field('GILLII_REPOSITORY')
(root/'dist').mkdir(exist_ok=True);archive=root/'dist'/f'gillii-{version}.tar.gz'
mtime=int(datetime.datetime.fromisoformat(date).replace(tzinfo=datetime.timezone.utc).timestamp())
with archive.open('wb') as raw,gzip.GzipFile(filename='',mode='wb',fileobj=raw,mtime=0) as compressed,tarfile.open(fileobj=compressed,mode='w') as tar:
 for p in sorted(root.rglob('*')):
  rel=p.relative_to(root)
  if any(x in rel.parts for x in ['.git','node_modules','dist','Formula']) or p.is_dir():continue
  info=tar.gettarinfo(str(p),arcname=f'gillii-{version}/{rel}')
  info.mtime=mtime;info.uid=info.gid=0;info.uname=info.gname=''
  with p.open('rb') as f:tar.addfile(info,f)
sha=hashlib.sha256(archive.read_bytes()).hexdigest()
(root/'dist'/f'gillii-{version}.sha256').write_text(f'{sha}  {archive.name}\n')
formula=f'''# Local development Formula. Not a published release URL.
# Generated by scripts/package.sh against a real source archive.
class Gillii < Formula
  desc "Locate, decrypt and restore cached WeChat mini-program packages"
  homepage "{repo}"
  url "{archive.as_uri()}"
  version "{version}"
  sha256 "{sha}"
  license "GPL-3.0-or-later"

  depends_on "node"

  def install
    libexec.install "bin", "lib", "libexec", "completions", "man", "LICENSE", "THIRD-PARTY.md"
    bin.write_exec_script libexec/"bin/gillii"
    man1.install libexec/"man/gillii.1"
    bash_completion.install (libexec/"completions/gillii.bash") => "gillii"
    zsh_completion.install (libexec/"completions/gillii.zsh") => "_gillii"
    fish_completion.install (libexec/"completions/gillii.fish") => "gillii.fish"
  end

  def caveats
    "Run gillii setup to install locked user-cache dependencies before recovery."
  end

  test do
    expected = "gillii version {version} ({date})\\n{repo}\\n"
    assert_equal expected, shell_output("#{{bin}}/gillii version")
    assert_equal expected, shell_output("#{{bin}}/gillii --version")
    assert_match "Copy, decrypt", shell_output("#{{bin}}/gillii help run")
    (testpath/"cache/wx0123456789abcdef/1").mkpath
    (testpath/"cache/wx0123456789abcdef/1/__APP__.wxapkg").write "fixture"
    result = JSON.parse(shell_output("#{{bin}}/gillii list --root #{{testpath}}/cache"))
    assert_equal "wx0123456789abcdef", result.fetch("packages").first.fetch("appid")
    assert_match "version", shell_output("#{{bin}}/gillii versoin 2>&1", 1)
    assert_path_exists man1/"gillii.1"
    assert_path_exists bash_completion/"gillii"
    assert_path_exists zsh_completion/"_gillii"
    assert_path_exists fish_completion/"gillii.fish"
  end
end
'''
(root/'Formula').mkdir(exist_ok=True);(root/'Formula/gillii.rb').write_text(formula)
print(f'{archive}\nSHA256 {sha}')
PY
